
package com.jeecourse.account.ws.v1.beans;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "wsException", targetNamespace = "http://www.jeecourse.com/account/v1")
public class WsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WsException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public WsException_Exception(String message, WsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public WsException_Exception(String message, WsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.jeecourse.account.ws.v1.beans.WsException
     */
    public WsException getFaultInfo() {
        return faultInfo;
    }

}
