
package com.jeecourse.account.ws.v1.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

import com.jeecourse.account.ws.v1.beans.AccountReq;
import com.jeecourse.account.ws.v1.beans.AccountRsp;
import com.jeecourse.account.ws.v1.beans.Accounts;
import com.jeecourse.account.ws.v1.beans.Empty;
import com.jeecourse.account.ws.v1.beans.ObjectFactory;
import com.jeecourse.account.ws.v1.beans.PaginationInfo;
import com.jeecourse.account.ws.v1.beans.WsException_Exception;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "accountManagementApi", targetNamespace = "http://www.jeecourse.com/account/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AccountManagementApi {


    /**
     * 
     * @param createAccountRequest
     * @return
     *     returns com.jeecourse.account.ws.v1.beans.AccountRsp
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "createAccountResponse", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "createAccountResponse")
    public AccountRsp createAccount(
        @WebParam(name = "createAccountRequest", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "createAccountRequest")
        AccountReq createAccountRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param getAccountRequest
     * @return
     *     returns com.jeecourse.account.ws.v1.beans.AccountRsp
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "getAccountResponse", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "getAccountResponse")
    public AccountRsp getAccount(
        @WebParam(name = "getAccountRequest", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "getAccountRequest")
        long getAccountRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param getAccountsRequest
     * @return
     *     returns com.jeecourse.account.ws.v1.beans.Accounts
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "getAccountsResponse", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "getAccountsResponse")
    public Accounts getAccounts(
        @WebParam(name = "getAccountsRequest", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "getAccountsRequest")
        PaginationInfo getAccountsRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param updateAccountRequest
     * @return
     *     returns com.jeecourse.account.ws.v1.beans.Empty
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "updateAccountResponse", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "updateAccountResponse")
    public Empty updateAccount(
        @WebParam(name = "updateAccountRequest", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "updateAccountRequest")
        AccountReq updateAccountRequest)
        throws WsException_Exception
    ;

    /**
     * 
     * @param deleteAccountRequest
     * @return
     *     returns com.jeecourse.account.ws.v1.beans.Empty
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "deleteAccountResponse", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "deleteAccountResponse")
    public Empty deleteAccount(
        @WebParam(name = "deleteAccountRequest", targetNamespace = "http://www.jeecourse.com/account/v1", partName = "deleteAccountRequest")
        long deleteAccountRequest)
        throws WsException_Exception
    ;

}
